spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ancate
    username: postgres
    password: postgres

server:
  servlet:
    context-path: /rakus-questionnaire

#mybatis設定
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  config-location: classpath:/config/mybatis.xml
  check-config-location: true

logging:
  level:
    org:
      springframework: WARN
    com:
      example:
        demo:
          mapper:
            EmployeeMapper: DEBUG
            QuestionnaireMapper: DEBUG